# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: coverage

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        runner: [ 'ubuntu-24.04' ]
        go: [ '1.25.1' ]

    runs-on: ${{ matrix.runner }}

    name: ${{ matrix.runner }}, golang:${{ matrix.go }}

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.COVERAGE_BADGE_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: |
            go.sum

      - name: Test
        run: go clean -testcache && go test -race -coverprofile=coverage.out -cover ./...

      - name: Coverage
        run: go tool cover -html=./coverage.out -o ./coverage.html

      - name: Update coverage badge
        run: |
          go install github.com/AlexBeauchemin/gobadge@latest
          gobadge -text="Go Coverage" -filename=coverage.out
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git commit --message "Update coverage badge" README.md
          git push
